### ISSUE TITLE
CraftTreeHandler.AddTabNode issue with tab names

### ISSUE THREAD

**Issue by RamuneNeptune** [SubnauticaModding/Nautilus-Proto#26]
When adding a custom tab node there is an issue with the names:

<code>CraftTreeHandler.AddTabNode(CraftTree.Type.Fabricator, "Test", "Test", SpriteManager.Get(TechType.Peeper);</code>
![](https://i.imgur.com/BUOkpoC.png)

<code>CraftTreeHandler.AddTabNode(CraftTree.Type.Workbench, "Test", "Test", SpriteManager.Get(TechType.Peeper);</code>
![](https://i.imgur.com/WjOuymM.png)

<code>CraftTreeHandler.AddTabNode(CraftTree.Type.Constructor, "Test", "Test", SpriteManager.Get(TechType.Peeper);</code>
![](https://i.imgur.com/KMaGITY.png)

**Comment by LeeTwentyThree** [comment]
See https://github.com/SubnauticaModding/Nautilus/issues/319.
