### ISSUE TITLE
BepInEx ConfigEntry extensions missing parameters

### ISSUE THREAD

**Issue by JKohlman** [SubnauticaModding/Nautilus-Proto#28]
Some of the extensions for creating `OptionItem` instances from BepInEx `ConfigEntry` instances are lacking a couple of parameters. I'll need to investigate a bit this week sometime but a known one is tooltip and defaultValue on choice options.

**Comment by LeeTwentyThree** [comment]
See https://github.com/SubnauticaModding/Nautilus/issues/317.
