### ISSUE TITLE
Mods tab issues with SMLHelper installed

### ISSUE THREAD

**Issue by RamuneNeptune** [SubnauticaModding/Nautilus-Proto#32]
The logfile provided no errors, and nothing out of the ordinary. So the logfile was basically a carbon copy of when I launch the game without SMLHelper installed

**Video**:
https://www.youtube.com/watch?v=eQOMFIRIB2s

**Comment by LeeTwentyThree** [comment]
See https://github.com/SubnauticaModding/Nautilus/issues/314.
